### ISSUE TITLE
Local variable is declared far before being used.

### ISSUE THREAD

**Issue by enrikb** [zeno420/Fowler#10]
Here:
https://github.com/zeno420/Fowler/blob/9a6ec8e4fecaea63cf91e70d283de5394c36ff34/src/Customer.java#L25
the local variable is declared, but used only 3 lines or so below.
Fowler writes he wants to get rid of this local variable, as it's only assigned once and never changed thereafter.
I would suggest to keep it, as it is actually _used_ more than once and the calculation could have side effects (which might be an issue of its own, but you never know...)
Therefore, my suggestion is to keep it, but declare it on first use instead.

**Comment by zeno420** [comment]
i will look into it.
/cib

**Comment by zeno420** [comment]
i will look into it.
